<?php $this->layout('layout::default', ['title' => 'Código de Conduta']) ?>

<a href="#top" class="text-muted back-to-top"><em class="fa fa-toggle-up"></em>&nbsp;Back to top</a>
<div class="content">
    <div itemtype="http://schema.org/SoftwareSourceCode">
        <main>
            <div class="px-3">
                <div class="container-fluid">
                    <div class="row">
                        <?= $this->insert('app::nav') ?>
                        <div class="repository-content content">
                            <div class="Box Box--condensed">
                                <div class="Box-body p-5">
                                    <article class="markdown-body container-lg" itemprop="text">
                                        <h1>
                                            <a id="codigo-de-conduta" class="anchor" aria-hidden="true" href="#codigo-de-conduta">
                                                <svg class="octicon octicon-link" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
                                                </svg>
                                            </a>
                                            Código de conduta do colaborador
                                        </h1>
                                        <p>Este projeto adere ao <a href="http://codemanifesto.com" target="_blank">The Code Manifesto</a>.</p>
                                        <h2 id="manifesto-do-c-digo">Manifesto do Código</h2>
                                        <p>Queremos trabalhar em um ecossistema que capacita desenvolvedores a atingir todo seu potencial, que encoraja crescimento e colaboração. Um espaço que seja seguro para todos.</p>
                                        <p>Um espaço como este beneficia a todos que dele participam. Encoraja novos desenvolvedores a entrar em nosso campo. É através da discussão e colaboração que nós crescemos, e através do crescimento que nós melhoramos.</p>
                                        <p>No esforço de criar tal lugar, sustentamos estes valores:</p>
                                        <ol>
                                            <li><strong>Discriminação nos limita.</strong> Isso inclui a discriminação com base em raça, sexo, orientação sexual, identidade de gênero, idade, nacionalidade ou qualquer outra exclusão arbitrária de um grupo de pessoas.</li>
                                            <li><strong>Limites nos honram.</strong> Seus níveis de conforto não são os níveis de conforto de todos. Lembre-se disso e, se alguém chamar a sua atenção, acate.</li>
                                            <li><strong>Somos nosso maior patrimônio.</strong> Nenhum de nós nasceu mestre. Cada um de nós foi ajudado durante o caminho, devolva o favor, quando e onde puder.</li>
                                            <li><strong>Somos recursos para o futuro.</strong> Uma extensão do item #3, compartilhe seu conhecimento. Transforme-se em um recurso de auxílio àqueles que vierem depois de você.</li>
                                            <li><strong>Respeito nos define.</strong> Trate os outros como gostaria de ser tratado. Discuta, critique e debata respeitosamente. Pergunte-se: isso é verdade? Isso é necessário? Isso é construtivo? Qualquer outra coisa não é tolerável.</li>
                                            <li><strong>Reações requerem bondade.</strong> Respostas raivosas são válidas, mas o uso de linguagem abusiva e vingativa é tóxico. Quando algo ofensivo acontecer a você, lide com isso de forma assertiva, mas sendo respeitoso. Seja razoável, dando a oportunidade à pessoa que o ofendeu de explicar-se, e, se possível, corrigir o problema.</li>
                                            <li><strong>As opiniões são apenas isso: opiniões.</strong> Todos e cada um de nós, devido à nossa formação e educação, têm diferentes opiniões. De fato, isso é perfeitamente aceitável. Lembre-se: se você respeitar suas próprias opiniões, você deve respeitar as opiniões dos outros.</li>
                                            <li><strong>Errar é humano.</strong> Você pode não querer, mas erros acontecem. Tolere erros genuínos e não hesite em se desculpar se você fizer o mesmo.</li>
                                        </ol>
                                    </article>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
