<nav>
    <div class="resource-group">
        <div class="heading">
            <div class="chevron"><em class="open fa fa-angle-down"></em></div>
            <a href="#top">Content</a>
        </div>
        <div class="">
            <ul>
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="/comments">Comentários</a>
                </li>
                <li>
                    <a href="/resources">Recursos</a>
                </li>
                <li>
                    <a href="/setup">Configuração do ambiente de desenvolvimento</a>
                <li>
                <li>
                    <a href="/commit-standards">Padrões de commit</a>
                </li>
                <li>
                    <a href="/coding-standards">Padrões de codificação</a>
                </li>
                <li>
                    <a href="/conduct-code">Código de Conduta</a>
                </li>
                <li>
                    <a href="/todo">To do List</a>
                </li>
                <li>
                    <a href="/documentation">Documentação da API</a>
                </li>
                <li>
                    <a href="/test-coverage/unit">Cobertura de Testes Unitários</a>
                </li>
                <li>
                    <a href="/test-coverage/integration">Cobertura de Testes de Integração</a>
                </li>
                <li>
                    <a href="/matches">Agenda de jogos <span class="badge badge-danger badge-pill ml-1">Top</span></a>
                </li>
            </ul>
        </div>
    </div>
    <p style="text-align: center; word-wrap: break-word;">
        <a href="https://selecao-globo.herokuapp.com" target="_blank">https://selecao-globo.herokuapp.com</a>
    </p>
</nav>
