<?php $this->layout('layout::default', ['title' => 'Recursos']) ?>

<a href="#top" class="text-muted back-to-top"><em class="fa fa-toggle-up"></em>&nbsp;Back to top</a>
<div class="content">
    <div itemtype="http://schema.org/SoftwareSourceCode">
        <main>
            <div class="px-3">
                <div class="container-fluid">
                    <div class="row">
                        <?= $this->insert('app::nav') ?>
                        <div class="repository-content content">
                            <div class="Box Box--condensed">
                                <div class="Box-body p-5">
                                    <article class="markdown-body container-lg" itemprop="text">
                                        <h1>
                                            <a id="recursos" class="anchor" aria-hidden="true" href="#recursos">
                                                <svg class="octicon octicon-link" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
                                                </svg>
                                            </a>
                                            Recursos
                                        </h1>
                                        <ul>
                                            <li><p><a href="https://www.nginx.com/" target="_blank" rel="nofollow">NGINX</a> - High Performance Load Balancer, Web Server, &amp; Reverse Proxy.</p></li>
                                            <li>
                                                <p><a href="https://www.php.net/" target="_blank" rel="nofollow">PHP</a> - PHP is a popular general-purpose scripting language that is especially suited to web development.</p>
                                                <ul>
                                                    <li><strong>Módulos:</strong>
                                                        <ul>
                                                            <li>apcu</li>
                                                            <li>bcmath</li>
                                                            <li>curl</li>
                                                            <li>gd</li>
                                                            <li>json</li>
                                                            <li>newrelic</li>
                                                            <li>opcache</li>
                                                            <li>redis</li>
                                                        </ul>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li>
                                                <p><a href="https://redis.io/" target="_blank" rel="nofollow">Redis</a> - Redis is an open source (BSD licensed), in-memory data structure store, used as a database, cache and message broker.</p>
                                                <ul>
                                                    <li><strong>Hosts:</strong>
                                                        <ul>
                                                            <li>
                                                                <em>http://localhost:6379</em>
                                                            </li>
                                                        </ul>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li>
                                                <p><a href="https://aws.amazon.com/pt/elasticsearch-service/the-elk-stack/" target="_blank" rel="nofollow">ELK</a> - The ELK stack is an acronym used to describe a stack that comprises of three popular open-source projects: Elasticsearch, Logstash, and Kibana.</p>
                                                <ul>
                                                    <li>
                                                        <strong>Host:</strong> <em>http://localhost:5601</em>
                                                    </li>
                                                    <li>
                                                        <strong>Index:</strong> <em>logstash-globo</em>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </article>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
