<?php $this->layout('layout::default', ['title' => 'Configuração']) ?>

<a href="#top" class="text-muted back-to-top"><em class="fa fa-toggle-up"></em>&nbsp;Back to top</a>
<div class="content">
    <div itemtype="http://schema.org/SoftwareSourceCode">
        <main>
            <div class="px-3">
                <div class="container-fluid">
                    <div class="row">
                        <?= $this->insert('app::nav') ?>
                        <div class="repository-content content">
                            <div class="Box Box--condensed">
                                <div class="Box-body p-5">
                                    <article class="markdown-body container-lg" itemprop="text">
                                        <h1>
                                            <a id="setup-do-ambiente-de-desenvolvimento" class="anchor" aria-hidden="true" href="#setup-do-ambiente-de-desenvolvimento">
                                                <svg class="octicon octicon-link" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
                                                </svg>
                                            </a>
                                            Configuração do ambiente de desenvolvimento
                                        </h1>
                                        <p>A aplicação fornece um <em>docker-compose.yml</em> para uso com <a href="https://docs.docker.com/compose/" target="_blank" rel="nofollow">docker-compose</a>.</p>
                                        <p>Será executado os seguintes serviços:</p>
                                        <ul>
                                            <li><strong>globo-nginx</strong>: image: nginx:latest</li>
                                            <li><strong>globo-php</strong>: image: php:7.4-fpm</li>
                                            <li><strong>globo-redis</strong>: image: redis:latest</li>
                                            <li><strong>globo-elk</strong>: image: sebp/elk:latest</li>
                                            <li><strong>globo-cron</strong>: image: php:7.4-fpm-alpine</li>
                                            <li><strong>globo-sonarqube</strong>: image: sonarqube:7.9.4-community</li>
                                            <li><strong>globo-webgrind</strong>: image: jokkedk/webgrind:latest</li>
                                        </ul>
                                        <p>Construa e inicie a imagem usando os comandos:</p>
                                        <div class="highlight highlight-source-shell">
                                            <?= $this->insert('app::setup-commands') ?>
                                        </div>
                                        <p>Ou simplestemente usando o atalho fornecido:</p>
                                        <div class="highlight highlight-source-shell">
                                            <pre><span class="code-text">$ bin/runenv.sh</span></pre>
                                        </div>
                                        <p>Neste ponto, você pode visitar <a href="http://localhost:8181" rel="nofollow">http://localhost:8181</a> (HTTP/HTTP1.1) ou <a href="https://localhost:8282" rel="nofollow">https://localhost:8282</a> (HTTPS/HTTP2.0) para testar a execução da aplicação. </p>
                                        <p>Agora você deve estar pronto para utilizar a aplicação!</p>
                                    </article>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
