sonar.host.url=http://172.17.0.1:99
sonar.projectKey=globo
sonar.projectName=globo
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.tests=./test
sonar.exclusions=bin/**/*, cache/**/*, config/**/*, data/**/*, docker/**/*, esportes-api/**/*, public/assets/plugin/**/*, target/**/*, test/**/*, vendor/**/*
sonar.php.tests.reportPath=target/unit/report.xml
sonar.php.coverage.reportPaths=target/unit/coverage.xml, target/integration/coverage.xml
sonar.log.console=true
sonar.login=
