<?php
$response = [
    "success" => false,
    "message" => "Oops! We encountered a 404 Not Found error.",
    "reason" => "You are looking for something that doesn't exist or may have moved."
];

header('Content-Type: application/json');

try {
    echo json_encode($response, JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT | JSON_FORCE_OBJECT);
} catch (JsonException $e) {
    echo $e->getCode() . ':' . $e->getMessage();
}
